# Generated by Django 4.1.4 on 2023-01-11 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='idClassroom',
            field=models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom'),
        ),
    ]
