version: '3.8'

services:
  app: 
    build: . 
    container_name: taller-forms
    ports: 
      - 8000:8000
    volumes:
      - .:/app/

networks:
  default: 
    name: development 
    external: True